---
title: Team
toc: false
author: ""
title-block-banner: false
page-layout: article
format:
  html:
    html-math-method: katex


toc-title: Year
toc-location: right
date-format: "MMMM D, YYYY"
image: ""
code-tools: false
comments: false
---


## Post-docs
- Jean-Baptiste Fermanian 2023-2024

## Ph.D. Students
- [Antoine Simoes](https://fr.linkedin.com/in/antoine-simoes-4a2b67197): co-supervised by [Yohann de Castro](https://ydecastro.github.io/) 2022-2025?

<!-- ## Engineers -->



## Alumni
- [Tanguy Lefort](https://tanglef.github.io/) [Ph.D. 2021-2024] co-supervised with [Benjamin Charlier](https://imag.umontpellier.fr/~charlier/index.php?page=index) and [Alexis Joly](http://www-sop.inria.fr/members/Alexis.Joly/wiki/pmwiki.php) (now post-doctorate at Inria Lille)
- [Axel Dubar](https://github.com/axeldubarp) 2023-2024, now Ph.D. student at Univ. Montpellier.
- [Camille Garcin](https://garcinc.github.io/Camille-Garcin/) [Ph.D. 2020-2023] co-supervised by [Alexis Joly](http://www-sop.inria.fr/members/Alexis.Joly/wiki/pmwiki.php) and [Maximilien Servajean](https://maximiliense.github.io/) (now post-doctorate at Inria Montpellier)
- [Emmanuel Pilliat](https://epilliat.github.io/Page-perso/) [Ph.D. 2020-2023] co-supervised by [Nicolas Verzelen](http://nicolas.verzelen.free.fr/) and [Alexandra Carpentier](https://sites.google.com/site/alexandracarpentierresearch/http://nicolas.verzelen.free.fr/) (now assistant professor at ENSAI)
- [Hashem Ghanem](https://hashemghanem.github.io/) [Ph.D. 2020-2023] co-supervised by [Samuel Vaiter](https://samuelvaiter.com/) and [Nicolas Keriven](https://nkeriven.github.io/) (now datascientist at Expleo)
- [Damien Blanc](https://www.quantacell.com/about/) [Ph.D. 2019-2022], co-supervised by [Benjamin Charlier](https://imag.umontpellier.fr/~charlier/index.php?page=index) and funded by [Quantacell](https://www.quantacell.com/)
- [Cassio Fraga Dantas](https://cassiofragadantas.github.io/) Post-doctorate associate: 2022, (now at Researcher at INRAE) </br>
- [Florent Bascou](https://bascouflorent.github.io) [Ph.D. 2019-2022], co-supervised by [Sophie Lèbre](http://www.univ-montp3.fr/miap/~lebre/), </br>
Manuscript: ["Sparse linear model with quadratic interactions"](/papers/these_bascou.pdf)
- [Quentin Bertrand](https://qb3.github.io/) [Ph.D. 2018-2021], co-supervised by [Alexandre Gramfort](http://alexandre.gramfort.net/) (now at Mila), </br>
Manuscript: ["Hyperparameter selection for high dimensional sparse learning : application to neuroimaging"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-03373531)
- [Nidham Gazagnadou](https://ngazagna.github.io/) [Ph.D. 2018-2021] co-supervised by [Robert Gower](https://perso.telecom-paristech.fr/rgower/) (now at Sony AI), </br>
Manuscript: ["Expected smoothness for stochastic variance-reduced methods and sketch-and-project methods for structured linear systems"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-03590678)
- [Pierre-Antoine Bannier](https://twitter.com/el_pa_b) [Intern 2021], co-supervised by [Alexandre Gramfort](http://alexandre.gramfort.net/)
- [Jérôme-Alexis Chevalier](https://ja-che.github.io/) [Ph.D. 2017-2020], co-supervised by [Bertrand Thirion](https://team.inria.fr/parietal/team-members/bertrand-thirions-page/) (Senior Data Scientist at Emerton Data), </br>
Manuscript: ["Statistical control of sparse models in high dimension"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-03147200v1)
- [Mathurin Massias](https://mathurinm.github.io) [Ph.D. 2016-2019], co-supervised by [Alexandre Gramfort](http://alexandre.gramfort.net/) (now CR INRIA, Lyon), </br>
Manuscript: ["Sparse high dimensional regression in the presence of colored heteroscedastic noise : application to M/EEG source imaging"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-02533661)
- [Evgenii Chzhen](https://echzhen.com/) [Ph.D. 2016-2019], co-supervised by [Mohamed Hebiri](http://perso-math.univ-mlv.fr/users/hebiri.mohamed/) (now CR CNRS, Saclay), </br>
Manuscript: ["Plug-in methods in classification"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-02400552v1)
- [Eugene Ndiaye](https://eugenendiaye.github.io/) [Ph.D., 2015-2018], co-supervised by [Olivier Fercoq](http://perso.telecom-paristech.fr/~ofercoq/) (now post-doctorate at GeorgiaTech), </br>
Manuscript: ["Safe optimization algorithms for variable selection and hyperparameter tuning"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-01962450v1)
- [Jean Lafond](http://perso.telecom-paristech.fr/~lafond/) [Ph.D., 2013-2016] co-supervised by [Éric Moulines](http://perso.telecom-paristech.fr/~moulines/) (now at Cubist Systematic, UK), </br>
Manuscript: ["Complétion de matrice : aspects statistiques et computationnels"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-01529861)
- [Igor Colin](http://perso.telecom-paristech.fr/~colin) [Ph.D., 2013-2016] co-supervised by [Stéphan Clémençon](http://perso.telecom-paristech.fr/~clemenco/) and funded by [Streamwide](http://www.streamwide.com/) (now at Huawei), </br>
Manuscript: ["Adapting machine learning methods to U-statistics"](https://jeannicod.ccsd.cnrs.fr/STAR/tel-01701636v1)
- [Jair Montoya](http://google.com) [Post Doc, 2016-2017], co-supervised by [Olivier Fercoq](http://perso.telecom-paristech.fr/~ofercoq/)
- [Thierry Guillemot](https://github.com/tguillemot) (now at ARIADNEXT) Engineer, co-supervised by [Alexandre Gramfort](http://alexandre.gramfort.net/), 2016