---
title: SD204 - linear models (2016-2018)
description: "Linear models and a bit of sparsity"
categories: [linear models, sparse models]
image: "images/fig_pca_axis2.svg"
reference-location: document
fig-cap-location: bottom
draft: false

# title-block-banner: hello-world-bg.jpg

format:
  html:
    include-before-body: ../html/margin_image.html
    include-after-body: ../html/blog_footer.html
    code-fold: true
---

This is an undergraduate course on linear models.

## Slides and Courses

1. Introduction: [LeastSquare_1D_en.pdf](enseignement/TELECOM/SD204/LeastSquare_1D_en.pdf), [LeastSquare_1D_en.ipynb](enseignement/TELECOM/SD204/LeastSquare_1D_en.ipynb), [LeastSquare_1D_en.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/LeastSquare_1D_en.ipynb)

1. Least squares : [LeastSquare_Def_en.pdf](enseignement/TELECOM/SD204/LeastSquare_Def_en.pdf), [LeastSquare_1D_fr.ipynb](enseignement/TELECOM/SD204/LeastSquare_Def_en.ipynb), [LeastSquare_Def_en.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/LeastSquare_Def_en.ipynb)

1. Least squares (properties) : [LeastSquare_Prop_fr.pdf](enseignement/TELECOM/SD204/LeastSquare_Prop_en.pdf)

1. SVD: [SVD_en.pdf](enseignement/TELECOM/SD204/SVD_en.pdf) (in French), [SVD.ipynb](enseignement/TELECOM/SD204/SVD.ipynb), [SVD.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/SVD.ipynb)

1. PCA: [PCA_en.pdf](enseignement/TELECOM/SD204/PCA_en.pdf)</a> (in French), [PCA.ipynb](enseignement/TELECOM/SD204/PCA.ipynb), [PCA.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/PCA.ipynb)

1. IntroIC: [IntroIC_en.pdf](enseignement/TELECOM/SD204/IntroIC_en.pdf) (in French), [IntroIC.ipynb](enseignement/TELECOM/SD204/IntroIC.ipynb), [IntroIC.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/IntroIC.ipynb)

1. Bootstrap: [Bootstrap_en.pdf](enseignement/TELECOM/SD204/Bootstrap_en.pdf),

1. IntroTests: [IntroTests_en.pdf](enseignement/TELECOM/SD204/IntroTests_en.pdf), [forward_variable_selection.ipynb](enseignement/TELECOM/SD204/forward_variable_selection.ipynb), [forward_variable_selection.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/forward_variable_selection.ipynb)

1. Ridge: [Ridge_en.pdf](enseignement/TELECOM/SD204/Ridge_en.pdf), [Ridge_en.ipynb](enseignement/TELECOM/SD204/Ridge_en.ipynb), [Ridge_en.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/Ridge_en.ipynb)

1. Lasso: [Lasso_en.pdf](enseignement/TELECOM/SD204/Lasso_en.pdf), [Lasso_fr.ipynb](enseignement/TELECOM/SD204/Lasso_fr.ipynb), [Lasso_fr.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/Lasso_fr.ipynb),
 [functions_Lasso.py](enseignement/TELECOM/SD204/functions_Lasso.py), [prox_collection.py](enseignement/TELECOM/SD204/prox_collection.py)

1. Coordinate descent: [CD_en.pdf](enseignement/TELECOM/SD204/CD_en.pdf) (in French), [CD_fr.ipynb](enseignement/TELECOM/SD204/CD_fr.ipynb), [CD_fr.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/CD_fr.ipynb)

1. GLM: [GLM_en.pdf](enseignement/TELECOM/SD204/GLM_en.pdf) (in French), [GLM_fr.ipynb](enseignement/TELECOM/SD204/GLM_fr.ipynb), [GLM_fr.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/GLM_fr.ipynb)

1. Generalization: [Generalization_en.pdf](enseignement/TELECOM/SD204/Generalization_en.pdf), [Generalization_fr.ipynb](enseignement/TELECOM/SD204/Generalization_fr.ipynb), [Generalization_fr.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/Generalization_fr.ipynb)


1. Categorical variables: [CategoricalVariables.ipynb](enseignement/TELECOM/SD204/CategoricalVariables.ipynb), [CategoricalVariables.html]( http://nbviewer.jupyter.org/url/josephsalmon.eu/enseignement/TELECOM/SD204/CategoricalVariables.ipynb)

<br>
<br>
<br>

